config/routes.rb
Reddit::Application.routes.draw do
  # devise gem created new routes
  devise_for :users, :controllers => { :omniauth_callback_packs => 'users/omniauth_callbacks'}
  # You can have the root of your site routed with "root"
  root 'frontpages#index'
  # Created CRUD(Create, Read, Update, Destroy)
  resources :frontpages

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :frontpage
end

app/models/frontpage.rb
class Frontpage < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  
  validates :title, :presence => true
  validates :description, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

  has_many :frontpages
  has_many :comments
  attr_accessor :login
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
  	devise_parameter_sanitizer.for(:sign_in) {|u| u.permit(:login, :username, :email, :password, :remember_me) }
  	devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

  # def configure_permitted_parameters
  # 	devise_parameter_sanitizer.for(:sign_in) {|u| u.permit(:username, :email) }
  # end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/frontpages_controller.rb
class FrontpagesController < ApplicationController
  before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]

  def index
    @frontpages = Frontpage.all.paginate(:page => params[:page], :per_page => 25).order("created_at ASC")
  end

  def new
    @frontpage = Frontpage.new
  end

  def create
    @frontpage = current_user.frontpages.create(frontpage_params)
    if @frontpage.valid?
    	redirect_to frontpages_path
    else
    	render :new, :status => :unprocessable_entity
    end
  end

  def show
    @frontpage = Frontpage.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @frontpage = Frontpage.find(params[:id])
    if @frontpage.user != current_user
    	render :text => 'Not allowed', :status => :unauthorized
    end
  end

  def update
    @frontpage = Frontpage.find(params[:id])
    if @frontpage.user != current_user
    	render :text => 'Not allowed', :status => :unauthorized
    end
    @frontpage.update_attributes(frontpage_params)
    if @frontpage.valid?
      redirect_to frontpages_path
    else
      render :edit, :status => :unprocessable_entity
    end
  end

  def destroy
    @frontpage = Frontpage.find(params[:id])
    if @frontpage.user != current_user
    	render :text => 'Not allowed', :status => :unauthorized
    end
    @frontpage.destroy
    redirect_to frontpage_path
  end

  private

  def frontpage_params
    params.require(:frontpage).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/frontpages_helper.rb
module FrontpagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/frontpages/edit.html.erb
<div class="reddit-box">
	<h3>Edit your submission</h3>
	<%= simple_form_for @frontpage do |f| %>
		<%= f.input :title %>
		<%= f.input :description %>
		<br />
		<%= f.submit 'Edit', :class => 'btn btn-primary' %>
	<% end %>
</div>

app/views/frontpages/index.html.erb
<% @frontpages.each do |frontpage| %>
	<div class="reddit-box">
		<h4><%= link_to frontpage.title, frontpage_path(frontpage) %></h4>
		<h4><%= frontpage.description %></h4>

		<% if frontpage.user.present? %>
			<small><%= frontpage.user.username %></small>
		<% end %>
	</div>
<% end %>

app/views/frontpages/new.html.erb
<div class="reddit-box col-xs-10 col-xs-offset-1">
	<h4>Enter info here</h4>
	<%= simple_form_for @frontpage do |f| %>
		<%= f.input :title %>
		<br />
		<%= f.input :description %>
		<br /><br />
		<%= f.submit 'Create', :class => 'btn btn-primary' %>
	<% end %>
</div>

app/views/frontpages/show.html.erb
<div class="reddit-box">
	<h2><%= @frontpage.title %></h2>
	<h4><%= @frontpage.description %></h4>
	<div class="pull-right">
		<% if current_user && current_user == @frontpage.user %>
			<%= link_to 'Edit', edit_frontpage_path(@frontpage), :class => 'btn btn-primary' %>
			<%= link_to 'Delete', frontpage_path(@frontpage), :method => :delete, :data => {:confirm => 'Are you sure you want to delete this?'}, :class => 'btn btn-danger' %>
		<% end %>
	</div>
</div>

<div class="clear"></div>
<%= simple_form_for @comment, :url => '#' do |f| %>
	<%= f.input :message %>
	<%= f.submit "Add a Comment", :class => 'btn btn-success' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role ="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Reddit', frontpages_path, :class => 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Submit new posts here', new_frontpage_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if notice.present? %>
  <p class="notice notice-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-info"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>